// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voqdtwqmzkzccwuqfcjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvcWR0d3Ftemt6Y2N3dXFmY2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjgwNTksImV4cCI6MjA2MzkwNDA1OX0.YJ7SYscsHKuNCKU0TXHlwvBDRzqPpQJJouVFZX_X5DE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);